schema = [
    {"name": "Id", "type": "UUID"},
    {"name": "CreatedOn", "type": "TIMESTAMP"},
    {"name": "CreatedById", "type": "UUID"},
    {"name": "ModifiedOn", "type": "TIMESTAMP"},
    {"name": "ModifiedById", "type": "UUID"},
    {"name": "Name", "type": "TEXT"},
    {"name": "Description", "type": "TEXT"},
    {"name": "Code", "type": "TEXT"},
    {"name": "ForContact", "type": "BOOLEAN"},
    {"name": "ForAccount", "type": "BOOLEAN"},
    {"name": "ProcessListeners", "type": "INTEGER"},
    {"name": "OkbCode", "type": "TEXT"},
    {"name": "EtlExecutionDate", "type": "TIMESTAMP"},
    {"name": "EtlStartDate", "type": "TIMESTAMP"},
]
