schema = [
    {"name": "Id", "type": "UUID"},
    {"name": "CreatedOn", "type": "TIMESTAMP"},
    {"name": "CreatedById", "type": "UUID"},
    {"name": "ModifiedOn", "type": "TIMESTAMP"},
    {"name": "ModifiedById", "type": "UUID"},
    {"name": "Request", "type": "TEXT"},
    {"name": "Response", "type": "TEXT"},
    {"name": "RequestDate", "type": "TIMESTAMP"},
    {"name": "ResponseDate", "type": "TIMESTAMP"},
    {"name": "Status", "type": "INTEGER"},
    {"name": "RequestUrl", "type": "TEXT"},
    {"name": "ApplicationId", "type": "UUID"},
    {"name": "Error", "type": "TEXT"},
    {"name": "ProcessListeners", "type": "INTEGER"},
    {"name": "ContactId", "type": "UUID"},
    {"name": "EtlExecutionDate", "type": "TIMESTAMP"},
    {"name": "EtlStartDate", "type": "TIMESTAMP"},
]
