CREATE TABLE [tz].[Cashflow](
	[BatchId]					BIGINT				NOT NULL,
	[EffectiveDate]				DATETIME    			NULL,
	[AccountId]					UNIQUEIDENTIFIER		NULL,
	[ActualDate]				DATETIME    			NULL,
	[ActualDateDT]				DATE					NULL,
	[Amount]					NUMERIC(18, 2)			NULL,
	[ApplicationId]				UNIQUEIDENTIFIER		NULL,
	[CampaignId]				UNIQUEIDENTIFIER		NULL,
	[CashflowId]				UNIQUEIDENTIFIER		NULL,
	[CashflowSourceId]			UNIQUEIDENTIFIER		NULL,
	[Cashless]					BIT						NULL,
	[CategoryId]				UNIQUEIDENTIFIER		NULL,
	[ContactId]					UNIQUEIDENTIFIER		NULL,
	[ContractId]				UNIQUEIDENTIFIER		NULL,
	[CreatedOn]					DATETIME    			NULL,
	[CreatedOnDT]				DATE					NULL,
	[CurrencyId]				UNIQUEIDENTIFIER		NULL,
	[CurrencyRate]				NUMERIC(18, 2)			NULL,
	[DateSendDC]				DATETIME    			NULL,
	[DateSendDCDT]				DATE					NULL,
	[DateSendIBD]				DATETIME    			NULL,
	[DateSendIBDDT]				DATE					NULL,
	[DocumentId]				UNIQUEIDENTIFIER		NULL,
	[EstimatedDate]				DATETIME    			NULL,
	[EstimatedDateDT]			DATE					NULL,
	[ExternalNumber]			NVARCHAR(100)			NULL,
	[IsAutoRepayment]			BIT						NULL,
	[IsSendDC]					BIT						NULL,
	[IsSendIBD]					BIT						NULL,
	[MarketingEventId]			UNIQUEIDENTIFIER		NULL,
	[Notes]						NVARCHAR(MAX)			NULL,
	[Number]					NVARCHAR(100)			NULL,
	[OperationId]				NVARCHAR(100)			NULL,
	[OwnerCashflowId]			UNIQUEIDENTIFIER		NULL,
	[OwnerId]					UNIQUEIDENTIFIER		NULL,
	[PaymentSystemAccountInfo]	NVARCHAR(500)			NULL,
	[PrimaryAmount]				NUMERIC(18, 2)			NULL,
	[SendTo1C]					BIT						NULL,
	[StatusId]					UNIQUEIDENTIFIER		NULL,
	[Subject]					NVARCHAR(500)			NULL,
	[TransactionID]				NVARCHAR(500)			NULL,
	[TransferTime]				DATETIME    			NULL,
	[TransferTimeDT]			DATE					NULL,
	[TypeId]					UNIQUEIDENTIFIER		NULL,
	[Vat]						NUMERIC(18, 2)			NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_tz_Cashflow_BatchId ON tz.Cashflow(BatchId, CashflowId) INCLUDE(EffectiveDate);
GO
GRANT DELETE, INSERT ON tz.Cashflow TO tz_report;

