CREATE TABLE tz.Product
(
	  BatchId                                   BIGINT           NOT NULL
    , EffectiveDate                             DATETIME         NOT NULL

	, ProductId                                 UNIQUEIDENTIFIER     NULL
    , [Name]                                    NVARCHAR(500)        NULL
    , Code                                      NVARCHAR(100)        NULL
    , UnitId                                    UNIQUEIDENTIFIER     NULL
    , CurrencyId                                UNIQUEIDENTIFIER     NULL
    , Price                                     NUMERIC(18,2)        NULL
    , TaxId                                     UNIQUEIDENTIFIER     NULL
    , Active                                    BIT                  NULL
    , [URL]                                     NVARCHAR(500)        NULL
    , TypeId                                    UNIQUEIDENTIFIER     NULL
    , OwnerId                                   UNIQUEIDENTIFIER     NULL
    , [Description]                             NVARCHAR(MAX)        NULL
    , ProductSourceId                           UNIQUEIDENTIFIER     NULL
    , Notes                                     NVARCHAR(MAX)        NULL
    , ClientProfile                             NVARCHAR(500)        NULL
    , AdditionalTerms                           NVARCHAR(500)        NULL
    , ActiveFrom                                DATE                 NULL
    , ActiveTo                                  DATE                 NULL
    , StatusId                                  UNIQUEIDENTIFIER     NULL
    , ClientTypeId                              UNIQUEIDENTIFIER     NULL
    , DaysTermMin                               INT                  NULL
    , DaysTermMax                               INT                  NULL
    , RubSumMin                                 NUMERIC(18,2)        NULL
    , RubSumMax                                 NUMERIC(18,2)        NULL
    , RatePerDay                                NUMERIC(18,3)        NULL
    , RubFineSum                                NUMERIC(18,3)        NULL
    , FineDay                                   INT                  NULL
    , ProlongationsMax                          INT                  NULL
    , StartDate                                 DATE                 NULL
    , EndDate                                   DATE                 NULL
    , [Default]                                 BIT                  NULL
    , [Priority]                                INT                  NULL
    , GraceOfDays                               INT                  NULL
    , FullCost                                  NUMERIC(18,3)        NULL
    , LoanApplicationAgreed                     INT                  NULL
    , Prolong                                   BIT                  NULL
    , ProlongMin                                INT                  NULL
    , ProlongMax                                INT                  NULL
    , ProlongParam                              NUMERIC(18,3)        NULL
    , StartRate                                 INT                  NULL
    , FinishRate                                INT                  NULL
    , RateDayLgot                               NUMERIC(18,3)        NULL
    , RateDayDelinLoan                          NUMERIC(18,3)        NULL
    , LimitOverpayment                          NUMERIC(18,3)        NULL
    , Freez                                     BIT                  NULL
    , Monday                                    BIT                  NULL
    , Tuesday                                   BIT                  NULL
    , Wednesday                                 BIT                  NULL
    , Thursday                                  BIT                  NULL
    , Friday                                    BIT                  NULL
    , Saturday                                  BIT                  NULL
    , Sunday                                    BIT                  NULL
    , StartFreez                                DATE                 NULL
    , EndFreez                                  DATE                 NULL
    , StartPenalties1                           INT                  NULL
    , FinishPenalties1                          INT                  NULL
    , Penalties1                                NUMERIC(18,3)        NULL
    , StartPenalties2                           INT                  NULL
    , FinishPenalties2                          INT                  NULL
    , Penalties2                                NUMERIC(18,3)        NULL
    , EndFineDay                                INT                  NULL
    , PromCode                                  BIT                  NULL
    , TypePeriodProlongId                       UNIQUEIDENTIFIER     NULL
    , ProductProlongTypeId                      UNIQUEIDENTIFIER     NULL
    , TypeProlongParamId                        UNIQUEIDENTIFIER     NULL
    , TypeLimitOverpaymentId                    UNIQUEIDENTIFIER     NULL
    , TypePenaltiesId                           UNIQUEIDENTIFIER     NULL
    , TypeFineId                                UNIQUEIDENTIFIER     NULL
    , ProductTimeFreezTypeId                    UNIQUEIDENTIFIER     NULL
    , IconId                                    UNIQUEIDENTIFIER     NULL
    , PeriodTypeId                              UNIQUEIDENTIFIER     NULL
    , FullCostV                                 NUMERIC(18,3)        NULL
    , LastProlongMin                            INT                  NULL
    , RateDayMax                                INT                  NULL
    , PenaltiesPay                              INT                  NULL
    , RatePay                                   INT                  NULL
    , TypePenalties1Id                          UNIQUEIDENTIFIER     NULL
    , TypePenalties2Id                          UNIQUEIDENTIFIER     NULL
    , FinePay                                   INT                  NULL
    , TypePeriodApplicationId                   UNIQUEIDENTIFIER     NULL
    , TypeLimitProlongId                        UNIQUEIDENTIFIER     NULL
    , TypeFineNewId                             UNIQUEIDENTIFIER     NULL
    , TypeLimitOverpaymentProcId                UNIQUEIDENTIFIER     NULL
    , LimitOverpaymentProc                      NUMERIC(18,3)        NULL
    , PeriodId                                  UNIQUEIDENTIFIER     NULL
    , IsLoanCount                               BIT                  NULL
    , RateDayProlong                            NUMERIC(18,3)        NULL
    , ProlongDay                                INT                  NULL
    , RateDayProlongLgot                        NUMERIC(18,3)        NULL
    , FreezNotAfterProlong                      BIT                  NULL
    , AppLimit                                  BIT                  NULL
    , AppLimitMax                               INT                  NULL
    , AppLimitPeriodId                          UNIQUEIDENTIFIER     NULL
    , FreezNumberDay                            NVARCHAR(1000)       NULL
    , FreezDay                                  NVARCHAR(1000)       NULL
    , PartialRepayment                          BIT                  NULL
    , PartialRepaymentDay                       INT                  NULL
    , EarlyRepayment                            BIT                  NULL
    , EarlyRepaymentDay                         INT                  NULL
    , StepSum                                   INT                  NULL
    , RateDayPartialRepay                       NUMERIC(18,3)        NULL
    , RateRepayRepaymentTypeId                  UNIQUEIDENTIFIER     NULL
    , DayProlongFirst                           INT                  NULL
    , DayProlongNext                            INT                  NULL
    , FreezDayLast                              INT                  NULL
    , AccrueProcEarlyRepayment                  BIT                  NULL
    , AccrueProcOverduePayment                  BIT                  NULL
    , AccrueProcDay                             INT                  NULL
    , MaxFreezDay                               INT                  NULL
    , AppLimitPeriodTypeId                      UNIQUEIDENTIFIER     NULL
    , StepPeriod                                INT                  NULL
    , IdentificationFull                        BIT                  NULL
    , IdentificationFullRepeat                  BIT                  NULL
    , IdentificationEasy                        BIT                  NULL
    , CommissionProlong                         NUMERIC(18,2)        NULL
    , CommissionProlongTypeId                   UNIQUEIDENTIFIER     NULL
    , CommissionSumTypeId                       UNIQUEIDENTIFIER     NULL
    , SumForPenaltiesTypeId                     UNIQUEIDENTIFIER     NULL
    , ChangeAccrueRepaymentTypeId               UNIQUEIDENTIFIER     NULL
    , CoefficientProlongation                   NVARCHAR(100)        NULL
    , FullIdentificationPeriod                  INT                  NULL
    , FullIdentificationPeriodTypeId            UNIQUEIDENTIFIER     NULL
    , EarlyRepaymentTypeId                      UNIQUEIDENTIFIER     NULL
    , PartialRepaymentTypeId                    UNIQUEIDENTIFIER     NULL
    , NtpId                                     NVARCHAR(100)        NULL
    , IsChange                                  BIT                  NULL
    , LimitAccrualPenalties                     BIT                  NULL
    , IdentificationEsia                        BIT                  NULL
    , CancelInterest                            BIT                  NULL
    , CancelInterestFrom                        INT                  NULL
    , CancelInterestTo                          INT                  NULL
    , AlternativeCalculation                    BIT                  NULL
    , AlternativeRatePerDate                    NUMERIC(18,3)        NULL
    , PaymentsNumberWithMaxRate                 INT                  NULL
    , PaymentsPercentWithReducedDebt            INT                  NULL
    , Refinancing                               BIT                  NULL
    , AutoProlong                               BIT                  NULL
    , AutoProlongDays                           INT                  NULL
    , AutoProlongDaysAfterDpd                   INT                  NULL
    , GracePeriod                               INT                  NULL
)
GO
CREATE CLUSTERED INDEX IX_tz_Product_BatchId ON tz.Product(BatchId, ProductId);
GO
CREATE NONCLUSTERED INDEX IX_tz_Product_ApplicationId ON tz.Product(BatchId) INCLUDE(EffectiveDate);
GO
GRANT DELETE, INSERT ON tz.Product TO tz_report;