CREATE TABLE pbi.[Application]
(
    Id                               BIGINT           NOT NULL             IDENTITY(1, 1)
                                                                           CONSTRAINT PK_pbi_Application PRIMARY KEY,
    BatchId                          BIGINT               NULL,
    DateKey                          BIGINT           NOT NULL,            --Дата обновления записи
    DateAlternateKey                 DATE             NOT NULL,
    EffectiveDateFrom                DATETIME             NULL,
    EffectiveDateTill                DATETIME             NULL,

    ApplicationId                    UNIQUEIDENTIFIER NOT NULL,
    Account_RK                       BIGINT           NOT NULL,
    ContactId                        UNIQUEIDENTIFIER NOT NULL,
    Customer_RK                      BIGINT           NOT NULL,
    DealNumber                       VARCHAR(255)         NULL,
    HasBD                            INT                  NULL,            --Флаг, что у данного клиента были/есть хотя бы один займ в БД
    LandingSource                    VARCHAR(MAX)         NULL,
    MarketingSource                  VARCHAR(MAX)         NULL,
    MarketingWeb                     VARCHAR(MAX)         NULL,
    ClientType                       VARCHAR(255)         NULL,
    ClientTypeDetail                 VARCHAR(255)         NULL,
    IsFirstApplication               BIT                  NULL,
    NumAppDay                        INT                  NULL,
    NumLoans                         INT                  NULL,
    NumLoansPdl                      INT                  NULL,
    NumLoansIL                       INT                  NULL,
    CreatedDatetime                  DATETIME             NULL,
    FillingDatetime                  DATETIME             NULL,
    ScoringDatetime                  DATETIME             NULL,
    GreyzoneDatetime                 DATETIME             NULL,
    FinalDecisionDatetime            DATETIME             NULL,
    ApproveDatetime                  DATETIME             NULL,
    RejectDatetime                   DATETIME             NULL,
    IssueDatetime                    DATETIME             NULL,
    DecisionGR                       VARCHAR(255)         NULL,
    Decision                         VARCHAR(255)         NULL,
    IsClientReject                   BIT                  NULL,
    IsPI                             BIT                  NULL,
    IsUprid                          BIT                  NULL,
    IsScan                           BIT                  NULL,
    IsResigning                      BIT                  NULL,
    IsAutoApprove                    BIT                  NULL,
    IsAutoIssue                      BIT                  NULL,
    CommentVerifier                  VARCHAR(255)         NULL,
    IsApprove                        BIT                  NULL,
    IsApprovePDL                     BIT                  NULL,
    IsApproveIL                      BIT                  NULL,
    ApproveAmt                       MONEY                NULL,
    ApproveAmtPDL                    MONEY                NULL,
    ApproveAmtIL                     MONEY                NULL,
    TimeFillingApplication           INT                  NULL,
    DefaultProduct                   VARCHAR(255)         NULL,
    DefaultTerm                      VARCHAR(255)         NULL,
    DefaultAmt                       MONEY                NULL,
    RequestProduct                   VARCHAR(255)         NULL,
    RequestProductDetail             VARCHAR(255)         NULL,
    RequestTerm                      DECIMAL(18, 2)       NULL,
    RequestAmt                       MONEY                NULL,
    LoanAmt                          MONEY                NULL,
    Product                          VARCHAR(255)         NULL,
    ProductDetail                    VARCHAR(255)         NULL,
    InterestRate                     DECIMAL(10,2)        NULL,
    TermContract                     INT                  NULL,
    PhoneNumber                      VARCHAR(256)         NULL,
    Surname                          VARCHAR(256)         NULL,
    [Name]                           VARCHAR(256)         NULL,
    Patronymic                       VARCHAR(256)         NULL,
    PassportSeries                   VARCHAR(100)         NULL,
    PassportNumber                   VARCHAR(100)         NULL,
    BirthDate                        DATE                 NULL,
    Age                              INT                  NULL,
    RegAct                           VARCHAR(256)         NULL,                                                    
    RegReg                           VARCHAR(256)         NULL,
    MaritalStatus                    VARCHAR(25)          NULL,
    Education                        VARCHAR(25)          NULL,
    Gender                           VARCHAR(10)          NULL,
    TypeEmployment                   VARCHAR(50)          NULL,
    WorkPosition                     VARCHAR(250)         NULL,
    Step_0                           BIT                  NULL,
    Step_1                           BIT                  NULL,
    Step_2                           BIT                  NULL,
    Step_3                           BIT                  NULL,
    Step_4                           BIT                  NULL,
    Step_5                           BIT                  NULL,
    Step_6                           BIT                  NULL,
    Step_7                           BIT                  NULL,
    SMEVIdentification               DATETIME             NULL,
    ESIAIdentification               DATETIME             NULL,
    OldIdentification                DATETIME             NULL,
    DocsIdentification               DATETIME             NULL,
    PFRIdentification                DATETIME             NULL,
    IsNewSpr                         BIT                  NULL,           --Новая СПР
    Email                            VARCHAR(256)         NULL,
    FinancingInstrumentId            UNIQUEIDENTIFIER     NULL,
    BIN                              VARCHAR(50)          NULL,
    LastFourDigits                   VARCHAR(50)          NULL,
    CardId                           VARCHAR(50)          NULL,
    ExpiresOn                        DATE                 NULL,
    NameCommentFinancinginstrument   VARCHAR(250)         NULL,
    --служебные поля
    FIO                              VARCHAR(150)         NULL,
    FullCostStartCalc                DATE                 NULL,           --Дата начала действия процентной ставки. Актуально для беспроцентных периодов
    FillingDateDT                    DATE                 NULL,
    BatchIdSource                    BIGINT               NULL            --Какой брался BatchId для этой выборки. Внимание! Может не совпадать с BatchId
);
GO
CREATE NONCLUSTERED INDEX IX_Application_DateKey ON pbi.[Application](DateKey ASC, EffectiveDateTill ASC);
GO
CREATE NONCLUSTERED INDEX IX_Application_EffectiveDateTill ON pbi.[Application] (EffectiveDateTill) INCLUDE (EffectiveDateFrom,ACCOUNT_RK);
GO
CREATE NONCLUSTERED INDEX IX_Application_BatchId ON pbi.[Application] (BatchId) INCLUDE (EffectiveDateFrom,ACCOUNT_RK);
GO
GRANT SELECT ON pbi.Application TO tz_report;