MERGE dbo.SOURCE_SYSTEM AS trg
USING
(
      SELECT 'TZ' AS SOURCE_SYSTEM_CD, 'Турбозайм фронт-офис DC1-TZ-CL[1-2].bpmonlinetz' AS SOURCE_DESCRIPTION
	  WHERE DB_NAME() = 'TZ_DDS'
	  UNION ALL
	  SELECT 'EQZ' AS SOURCE_SYSTEM_CD, 'Эквазайм фронт-офис DC1-EZ-CL[*].bpmonlinetz' AS SOURCE_DESCRIPTION
	  WHERE DB_NAME() = 'EZ_DDS'
)  AS src (SOURCE_SYSTEM_CD, SOURCE_DESCRIPTION)
ON    src.SOURCE_SYSTEM_CD = trg.SOURCE_SYSTEM_CD
WHEN NOT MATCHED BY TARGET THEN
	INSERT (SOURCE_SYSTEM_CD, SOURCE_DESCRIPTION)
	VALUES (src.SOURCE_SYSTEM_CD, src.SOURCE_DESCRIPTION)
WHEN NOT MATCHED BY SOURCE THEN
	DELETE
WHEN MATCHED THEN
	UPDATE SET
		  trg.SOURCE_DESCRIPTION = src.SOURCE_DESCRIPTION;
