schema = [
    {"name": "id", "type": "UUID"},
    {"name": "created_on", "type": "TIMESTAMP"},
    {"name": "created_by_id", "type": "UUID"},
    {"name": "modified_on", "type": "TIMESTAMP"},
    {"name": "modified_by_id", "type": "UUID"},
    {"name": "process_listeners", "type": "INTEGER"},
    {"name": "contact_id", "type": "UUID"},
    {"name": "number", "type": "TEXT"},
    {"name": "status_id", "type": "UUID"},
    {"name": "start_date", "type": "TIMESTAMP"},
    {"name": "end_date", "type": "TIMESTAMP"},
    {"name": "planned_end_date", "type": "TIMESTAMP"},
    {"name": "file_id", "type": "UUID"},
    {"name": "credit_limit_id", "type": "UUID"},
    {"name": "sum", "type": "NUMERIC"},
    {"name": "etl_execution_date", "type": "TIMESTAMP"},
    {"name": "etl_start_date", "type": "TIMESTAMP"},
]
