CREATE TABLE [marts].[PostBack](
    ReportDate           DATE               NULL,
	[ApplicationId]		 UNIQUEIDENTIFIER	PRIMARY KEY,
	[Number]			 VARCHAR(50)		NULL,
	[ContactId]			 UNIQUEIDENTIFIER	NULL,
	[Email]				 VARCHAR(255)		NULL,
	[ContactMobilePhone] VARCHAR(255)		NULL,
	[ContactSource]		 VARCHAR(100)		NULL,
	[SourceURL]			 VARCHAR(MAX)		NULL,
	[AppCount]			 INT				NULL,
	[LoanCount]			 INT				NULL,
	[ClientType]		 VARCHAR(50)		NULL,
	[CreatedOn]			 DATE				NULL,
	[FillingDate]		 DATE				NULL,
	[PaymentDate]		 DATE				NULL,
	[Product]			 VARCHAR(MAX)		NULL,
	[Decision]			 VARCHAR(MAX)		NULL,
	[SourceGroup]		 VARCHAR(MAX)		NULL,
	[AnswerURL]			 VARCHAR(MAX)		NULL,
	[AnswerURL3]		 VARCHAR(MAX)		NULL,
	[ProductId]			 UNIQUEIDENTIFIER	NULL,
	[ContactSourceId] 	 UNIQUEIDENTIFIER	NULL,
	[SourceGroupId]		 UNIQUEIDENTIFIER	NULL,
	[OfferSum]			 DECIMAL(18,2)		NULL,
	[ProductType]		 VARCHAR(MAX)		NULL,
	[wmid]				 VARCHAR(MAX)		NULL,
	[Cookie]			 VARCHAR(MAX)		NULL
) 
GO
CREATE NONCLUSTERED INDEX IX_report_PostBack ON [report].[PostBack](ReportDate);