CREATE TABLE stg.t_tz_bpm_additional_product (
	id uuid NULL,
	created_on timestamp NULL,
	created_by_id uuid NULL,
	modified_on timestamp NULL,
	modified_by_id uuid NULL,
	process_listeners int4 NULL,
	"name" text NULL,
	type_id uuid NULL,
	"active" bool NULL,
	obligatory bool NULL,
	priority int4 NULL,
	organization_id uuid NULL,
	start_date date NULL,
	end_date date NULL,
	period_type_id uuid NULL,
	sum_min numeric NULL,
	sum_max numeric NULL,
	form_page_id uuid NULL,
	amount numeric NULL,
	product_number_type_id uuid NULL,
	sum_type_id uuid NULL,
	text text NULL,
	main_document_type_id uuid NULL,
	commission_number_type_id uuid NULL,
	commission_amount numeric NULL,
	fixed_term int4 NULL,
	insurance_subject_id uuid NULL,
	payment_type_id uuid NULL,
	cooling_period int4 NULL,
	preselected bool NULL,
	hide_info bool NULL,
	etl_execution_date timestamp NULL,
	etl_start_date timestamp NULL
)
DISTRIBUTED REPLICATED;