CREATE TABLE conv.ACCRUAL
(
	  RK                BIGINT            NOT NULL IDENTITY(1, 1) CONSTRAINT PK_conv_ACCRUAL                     PRIMARY KEY
	, ID_OLD            SQL_VARIANT           NULL
	, SOURCE_SYSTEM_CD  VARCHAR(3)        NOT NULL                CONSTRAINT FK_conv_ACCRUAL_dbo_SOURCE_SYSTEM   FOREIGN KEY REFERENCES dbo.SOURCE_SYSTEM ON UPDATE CASCADE
	, [Source]          sysname               NULL
	, ID                UNIQUEIDENTIFIER  NOT NULL
);
GO
CREATE NONCLUSTERED COLUMNSTORE INDEX IX_conv_ACCRUAL_ID ON conv.ACCRUAL(ID, SOURCE_SYSTEM_CD);
GO
GRANT INSERT, DELETE, UPDATE, SELECT ON conv.ACCRUAL TO tz_report;