CREATE TABLE conv.APSK_CALCULATION_EVENT
(
	  RK                BIGINT       NOT NULL IDENTITY(1, 1) CONSTRAINT PK_conv_APSK_CALCULATION_EVENT                     PRIMARY KEY
	, ID                SQL_VARIANT  NOT NULL
	, SOURCE_SYSTEM_CD  VARCHAR(3)   NOT NULL                CONSTRAINT FK_conv_APSK_CALCULATION_EVENT_dbo_SOURCE_SYSTEM   FOREIGN KEY REFERENCES dbo.SOURCE_SYSTEM ON UPDATE CASCADE
	, [Source]          sysname          NULL
);
GO
CREATE INDEX IX_conv_APSK_CALCULATION_EVENT_ID ON conv.APSK_CALCULATION_EVENT(ID) INCLUDE(SOURCE_SYSTEM_CD);
GO
GRANT INSERT, DELETE, UPDATE, SELECT ON conv.APSK_CALCULATION_EVENT TO tz_report;