CREATE TABLE conv.CREDIT_LIMIT
(
	  RK                BIGINT       NOT NULL IDENTITY(1, 1) CONSTRAINT PK_conv_CREDIT_LIMIT                     PRIMARY KEY
	, ID                SQL_VARIANT  NOT NULL
	, SOURCE_SYSTEM_CD  VARCHAR(3)   NOT NULL                CONSTRAINT FK_conv_CREDIT_LIMIT_dbo_SOURCE_SYSTEM   FOREIGN KEY REFERENCES dbo.SOURCE_SYSTEM ON UPDATE CASCADE
	, [Source]          sysname          NULL
);
GO
CREATE INDEX IX_conv_CREDIT_LIMIT_ID ON conv.CREDIT_LIMIT(ID) INCLUDE(SOURCE_SYSTEM_CD);
GO
GRANT INSERT, DELETE, UPDATE, SELECT ON conv.CREDIT_LIMIT TO tz_report;