CREATE TABLE conv.CUSTOMER
(
	  RK                BIGINT            NOT NULL IDENTITY(1, 1) CONSTRAINT PK_conv_CUSTOMER PRIMARY KEY
	, SOURCE_SYSTEM_CD  VARCHAR(3)        NOT NULL                CONSTRAINT FK_conv_CUSTOMER_dbo_SOURCE_SYSTEM FOREIGN KEY REFERENCES dbo.SOURCE_SYSTEM ON UPDATE CASCADE
	, [Source]          sysname               NULL
	, ID                UNIQUEIDENTIFIER  NOT NULL
);
GO
CREATE NONCLUSTERED INDEX IX_conv_CUSTOMER_ID      ON conv.CUSTOMER (ID);
GO
GRANT INSERT, DELETE, UPDATE, SELECT ON conv.CUSTOMER TO tz_report;
GO