CREATE TABLE conv.FINANCING_INSTRUMENT_TYPE
(
	  RK                BIGINT       NOT NULL IDENTITY(1, 1) CONSTRAINT PK_conv_FINANCING_INSTRUMENT_TYPE                     PRIMARY KEY
	, ID                SQL_VARIANT  NOT NULL
	, SOURCE_SYSTEM_CD  VARCHAR(3)   NOT NULL                CONSTRAINT FK_conv_FINANCING_INSTRUMENT_TYPE_dbo_SOURCE_SYSTEM   FOREIGN KEY REFERENCES dbo.SOURCE_SYSTEM ON UPDATE CASCADE
	, [Source]          sysname          NULL
	                                                       , CONSTRAINT UX_conv_FINANCING_INSTRUMENT_TYPE_ID_SOURCE_SYSTEM_CD UNIQUE(ID, SOURCE_SYSTEM_CD) WITH (IGNORE_DUP_KEY = ON)
);
GO
CREATE INDEX IX_conv_FINANCING_INSTRUMENT_TYPE_ID ON conv.FINANCING_INSTRUMENT_TYPE(ID);
GO
GRANT INSERT, DELETE, UPDATE, SELECT ON conv.FINANCING_INSTRUMENT_TYPE TO tz_report;