CREATE TABLE conv.LEGAL_COLLECTION_CONTRACT_STATUS
(
	  RK                BIGINT       NOT NULL IDENTITY(1, 1) CONSTRAINT PK_conv_LEGAL_COLLECTION_CONTRACT_STATUS PRIMARY KEY
	, ID                SQL_VARIANT  NOT NULL
	, SOURCE_SYSTEM_CD  VARCHAR(3)   NOT NULL                CONSTRAINT FK_conv_LEGAL_COLLECTION_CONTRACT_STATUS_dbo_SOURCE_SYSTEM FOREIGN KEY REFERENCES dbo.SOURCE_SYSTEM ON UPDATE CASCADE
	, [Source]          sysname          NULL
	                                                       , CONSTRAINT UX_conv_LEGAL_COLLECTION_CONTRACT_STATUS_ID_SOURCE_SYSTEM_CD UNIQUE(ID, SOURCE_SYSTEM_CD) WITH (IGNORE_DUP_KEY = ON)
);
GO
CREATE INDEX IX_conv_LEGAL_COLLECTION_CONTRACT_STATUS_ID      ON conv.LEGAL_COLLECTION_CONTRACT_STATUS (ID);
GO
GRANT INSERT, DELETE, UPDATE, SELECT ON conv.LEGAL_COLLECTION_CONTRACT_STATUS TO tz_report;