CREATE TABLE conv.VERIFICATION_LIST_ITEM
(
	  RK                BIGINT       NOT NULL IDENTITY(1, 1) CONSTRAINT PK_conv_VERIFICATION_LIST_ITEM                     PRIMARY KEY
	, ID                SQL_VARIANT  NOT NULL
	, SOURCE_SYSTEM_CD  VARCHAR(3)   NOT NULL                CONSTRAINT FK_conv_VERIFICATION_LIST_ITEM_dbo_SOURCE_SYSTEM   FOREIGN KEY REFERENCES dbo.SOURCE_SYSTEM ON UPDATE CASCADE
	, [Source]          sysname          NULL
	                                                       , CONSTRAINT UX_conv_VERIFICATION_LIST_ITEM_ID_SOURCE_SYSTEM_CD UNIQUE(ID, SOURCE_SYSTEM_CD) WITH (IGNORE_DUP_KEY = ON)
);
GO
CREATE INDEX IX_conv_VERIFICATION_LIST_ITEM_ID ON conv.VERIFICATION_LIST_ITEM(ID);
GO
GRANT INSERT, DELETE, UPDATE, SELECT ON conv.VERIFICATION_LIST_ITEM TO tz_report;